// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxG_T4z_smfIqnzn-cn6AUvdmdJE67hDU',
    appId: '1:408544546321:android:ee1ab85a69fb4fba0aebb0',
    messagingSenderId: '408544546321',
    projectId: 'habo-fa79b',
    storageBucket: 'habo-fa79b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXuQ2dgrDefbS8jTCOFxkdTkJlYaCNCdI',
    appId: '1:408544546321:ios:88425a4d77d45c490aebb0',
    messagingSenderId: '408544546321',
    projectId: 'habo-fa79b',
    storageBucket: 'habo-fa79b.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXuQ2dgrDefbS8jTCOFxkdTkJlYaCNCdI',
    appId: '1:408544546321:ios:88425a4d77d45c490aebb0',
    messagingSenderId: '408544546321',
    projectId: 'habo-fa79b',
    storageBucket: 'habo-fa79b.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );
}
